"""rename department

Revision ID: 204eadf86b0b
Revises: e62a5d3c9564
Create Date: 2025-04-03 15:34:36.420177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204eadf86b0b'
down_revision = 'e62a5d3c9564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments', 'departments')
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    
    op.drop_table('department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments','department')
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    
    op.drop_table('departments')
    # ### end Alembic commands ###
